name: 'build-deb-action'
description: 'Build debian package.'
author: 'jiro4989'
inputs:
  package:
    description: 'Package name of debian package.'
    required: true
  package_root:
    description: 'Directory of release files.'
    required: true
  maintainer:
    description: 'Package maintainer name.'
    required: true
  version:
    description: 'Package version.'
    required: true
  installed_size:
    description: 'Package installed size. GitHub Actions set summarized byte size of `package_root` directory when this parameter is empty.'
    default: ''
    required: false
  depends:
    description: 'Package dependencies.'
    default: ''
    required: false
  pre_depends:
    description: 'Package pre-dependencies.'
    default: ''
    required: false
  homepage:
    description: 'Package homepage url.'
    default: ''
    required: false
  section:
    description: 'Package section.'
    default: ''
    required: false
  priority:
    description: 'Package priority.'
    default: ''
    required: false
  arch:
    description: 'Package architecture.'
    default: 'amd64'
    required: false
  desc:
    description: 'Package description.'
    default: 'no description'
    required: false
  compress_type:
    description: >
      Set the compression type used when building.
      Allowed types gzip, xz, zstd, none.
      Default is gzip.
    default: 'gzip'
    required: false
  keep_ownership:
    description: >
      If set to true, it creates the package keeping files' owner and group, otherwise they will be assigned to root
      Default is false.
    default: 'false'
    required: false
outputs:
  file_name:
    description: 'File name of resulting .deb file.'
runs:
  using: 'docker'
  image: 'docker://jiro4989/build-deb-action:4.2.1'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
