name: 'build-deb-action'
description: 'Build debian package.'
author: 'jiro4989'
inputs:
  package:
    description: 'Package name of debian package.'
    required: true
  package_root:
    description: 'Directory of release files.'
    required: true
  maintainer:
    description: 'Package maintainer name.'
    required: true
  version:
    description: 'Package version.'
    required: true
  depends:
    description: 'Package dependencies.'
    default: 'none'
    required: false
  arch:
    description: 'Package architecture.'
    default: 'amd64'
    required: false
  desc:
    description: 'Package description.'
    default: 'no description'
    required: false
runs:
  using: 'docker'
  image: 'docker://jiro4989/build-deb-action:2.4.0'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
